services:
  postgres:
    image: postgres:15
    container_name: mentora-postgres
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgressecret
      POSTGRES_DB: bubblelove
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
