apiVersion: v1
kind: Service
metadata:
  name: #APP#
  namespace: #NAMESPACE#
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: #APP#

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #APP#
  namespace: #NAMESPACE#
spec:
  selector:
    matchLabels:
      app: #APP#
  replicas: 1
  template:
    metadata:
      labels:
        app: #APP#
    spec:
      containers:
        - image: #IMAGE#
          name: #APP#
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              value: "${POSTGRES_USER}"
            - name: POSTGRES_PASSWORD
              value: "${POSTGRES_PASSWORD}"
            - name: OPENAI_API_KEY
              value: "${OPENAI_API_KEY}"