apiVersion: v1
kind: Service
metadata:
  name: mentora-app
  namespace: ${NAMESPACE}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mentora-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mentora-app
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: mentora-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mentora-app
    spec:
      containers:
        - image: ${IMAGE}
          name: mentora-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY